In [1407]:
!pip install pymysql
!pip install sqlalchemy
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
print('al libraries imported successfully')

Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.1.2)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)al libraries imported successfully

Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1408]:
#inserting data into the notebook 
df=pd.read_csv('Telco-Customer-Churn (1).csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [1409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [1410]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [1411]:
df.shape

(7043, 21)

In [1412]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [1413]:
#cleaning the numeric data & currency data
#idenify th numeric & currency data
numeric_data=['tenure','MonthlyCharges','TotalCharges','SeniorCitizen']
df[numeric_data].head()

   tenure  MonthlyCharges TotalCharges  SeniorCitizen
0       1           29.85        29.85              0
1      34           56.95       1889.5              0
2       2           53.85       108.15              0
3      45           42.30      1840.75              0
4       2           70.70       151.65              0

In [1414]:
#check the datatypes
df[numeric_data].dtypes

tenure              int64
MonthlyCharges    float64
TotalCharges       object
SeniorCitizen       int64
dtype: object

In [1415]:
#convert all to float
for col in numeric_data:
    df[col]=pd.to_numeric(
        df[col],errors='coerce'
    )

df[numeric_data].dtypes

tenure              int64
MonthlyCharges    float64
TotalCharges      float64
SeniorCitizen       int64
dtype: object

In [1416]:
#ccheck null values
df[numeric_data].isna().sum()

tenure             0
MonthlyCharges     0
TotalCharges      11
SeniorCitizen      0
dtype: int64

In [1417]:
#handle null values
mean_Total_Charges=np.mean(df['TotalCharges'])
#fill null values with the mean
df['TotalCharges']=df['TotalCharges'].fillna(mean_Total_Charges)

In [1418]:
#recheck if the null values are handled
df[numeric_data].isna().sum()

tenure            0
MonthlyCharges    0
TotalCharges      0
SeniorCitizen     0
dtype: int64

In [1419]:
#cleaning strings columns
text_data=['customerID', 'gender', 'Partner', 'Dependents','PhoneService', 'MultipleLines', 'InternetService',
          'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling','Churn']
df[text_data].head()

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,StreamingTV,StreamingMovies,Contract,PaperlessBilling,Churn
0,7590-VHVEG,Female,Yes,No,No,No phone service,DSL,No,No,Month-to-month,Yes,No
1,5575-GNVDE,Male,No,No,Yes,No,DSL,No,No,One year,No,No
2,3668-QPYBK,Male,No,No,Yes,No,DSL,No,No,Month-to-month,Yes,Yes
3,7795-CFOCW,Male,No,No,No,No phone service,DSL,No,No,One year,No,No
4,9237-HQITU,Female,No,No,Yes,No,Fiber optic,No,No,Month-to-month,Yes,Yes

In [1420]:
#check null values
df[text_data].isna().sum()

customerID          0
gender              0
Partner             0
Dependents          0
PhoneService        0
MultipleLines       0
InternetService     0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
Churn               0
dtype: int64

In [1421]:
#check data types
df[text_data].dtypes

customerID          object
gender              object
Partner             object
Dependents          object
PhoneService        object
MultipleLines       object
InternetService     object
StreamingTV         object
StreamingMovies     object
Contract            object
PaperlessBilling    object
Churn               object
dtype: object

In [1422]:
#remove leading and trailing spaces
for col in text_data:
    #remove leading spaces
    df[col]=df[col].str.strip()
    #standardize the text to one type of case
    df[col]=df[col].str.title()
    #remove multiple spaces inside the text
    df[col]=df[col].str.replace(r'\s+',' ',regex=True)
                      
df[text_data].head()

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,StreamingTV,StreamingMovies,Contract,PaperlessBilling,Churn
0,7590-Vhveg,Female,Yes,No,No,No Phone Service,Dsl,No,No,Month-To-Month,Yes,No
1,5575-Gnvde,Male,No,No,Yes,No,Dsl,No,No,One Year,No,No
2,3668-Qpybk,Male,No,No,Yes,No,Dsl,No,No,Month-To-Month,Yes,Yes
3,7795-Cfocw,Male,No,No,No,No Phone Service,Dsl,No,No,One Year,No,No
4,9237-Hqitu,Female,No,No,Yes,No,Fiber Optic,No,No,Month-To-Month,Yes,Yes

In [1423]:
#clean the column names
df.columns=(
df.columns.str.strip()
    .str.title()
)

In [1424]:
df.duplicated().sum()

0

In [1425]:
df.columns

Index(['Customerid', 'Gender', 'Seniorcitizen', 'Partner', 'Dependents',
       'Tenure', 'Phoneservice', 'Multiplelines', 'Internetservice',
       'Onlinesecurity', 'Onlinebackup', 'Deviceprotection', 'Techsupport',
       'Streamingtv', 'Streamingmovies', 'Contract', 'Paperlessbilling',
       'Paymentmethod', 'Monthlycharges', 'Totalcharges', 'Churn'],
      dtype='object')

In [1426]:
df['Monthlycharges'].max()

118.75

In [1427]:
df['Monthlycharges'].min()

18.25

In [1428]:
df['Monthlycharges'].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: Monthlycharges, dtype: float64

In [1429]:
df['Monthlycharges'].quantile([0, 0.25, 0.50, 0.75, 1])

0.00     18.25
0.25     35.50
0.50     70.35
0.75     89.85
1.00    118.75
Name: Monthlycharges, dtype: float64

In [1430]:
df['MonthlyChargesGroup'] = pd.cut(
    df['Monthlycharges'],
    bins=[18.25, 35.50, 70.35, 89.85, 118.75],
    labels=['Low', 'Medium', 'High', 'Very High'],
    include_lowest=True
)

In [1431]:
df['MonthlyChargesGroup'].value_counts().sort_index()

MonthlyChargesGroup
Low          1762
Medium       1766
High         1757
Very High    1758
Name: count, dtype: int64

In [1432]:
df['Totalcharges'].max()

8684.8

In [1433]:
df['Totalcharges'].min()

18.8

In [1434]:
df['Totalcharges'].describe()

count    7043.000000
mean     2283.300441
std      2265.000258
min        18.800000
25%       402.225000
50%      1400.550000
75%      3786.600000
max      8684.800000
Name: Totalcharges, dtype: float64

In [1435]:
df['Totalcharges'].quantile([0, 0.25, 0.50, 0.75, 1])

0.00      18.800
0.25     402.225
0.50    1400.550
0.75    3786.600
1.00    8684.800
Name: Totalcharges, dtype: float64

In [1436]:
df['TotalChargesGroup'] = pd.cut(
    df['Totalcharges'],
    bins=[18.80, 402.225, 1400.550, 3786.600, 8684.800],
    labels=['Low', 'Medium', 'High', 'Very High'],
    include_lowest=True
)

In [1437]:
df['TotalChargesGroup'].value_counts().sort_index()

TotalChargesGroup
Low          1761
Medium       1761
High         1760
Very High    1761
Name: count, dtype: int64

In [1438]:
df['Tenure'].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: Tenure, dtype: float64

In [1439]:
df['Tenure'].quantile([0, 0.25, 0.50, 0.75, 1])

0.00     0.0
0.25     9.0
0.50    29.0
0.75    55.0
1.00    72.0
Name: Tenure, dtype: float64

In [1440]:
df['Tenure'].value_counts().sort_index()

Tenure
0      11
1     613
2     238
3     200
4     176
     ...
68    100
69     95
70    119
71    170
72    362
Name: count, Length: 73, dtype: int64

In [1441]:
df['TenureGroup'] = pd.cut(
    df['Tenure'],
    bins=[-1, 12, 24, 48, 72],
    labels=['New', 'Early', 'Established', 'Long-term']
)

In [1442]:
df['TenureGroup'].value_counts().sort_index()

TenureGroup
New            2186
Early          1024
Established    1594
Long-term      2239
Name: count, dtype: int64

In [1443]:
df['Contract'].value_counts()

Contract
Month-To-Month    3875
Two Year          1695
One Year          1473
Name: count, dtype: int64

In [1444]:
df['Contract'].value_counts(normalize=True) * 100

Contract
Month-To-Month    55.019168
Two Year          24.066449
One Year          20.914383
Name: proportion, dtype: float64

In [1445]:
df.head()

,Customerid,Gender,Seniorcitizen,Partner,Dependents,Tenure,Phoneservice,Multiplelines,Internetservice,Onlinesecurity,...,Streamingmovies,Contract,Paperlessbilling,Paymentmethod,Monthlycharges,Totalcharges,Churn,MonthlyChargesGroup,TotalChargesGroup,TenureGroup
0,7590-Vhveg,Female,0,Yes,No,1,No,No Phone Service,Dsl,No,...,No,Month-To-Month,Yes,Electronic check,29.85,29.85,No,Low,Low,New
1,5575-Gnvde,Male,0,No,No,34,Yes,No,Dsl,Yes,...,No,One Year,No,Mailed check,56.95,1889.50,No,Medium,High,Established
2,3668-Qpybk,Male,0,No,No,2,Yes,No,Dsl,Yes,...,No,Month-To-Month,Yes,Mailed check,53.85,108.15,Yes,Medium,Low,New
3,7795-Cfocw,Male,0,No,No,45,No,No Phone Service,Dsl,Yes,...,No,One Year,No,Bank transfer (automatic),42.30,1840.75,No,Medium,High,Established
4,9237-Hqitu,Female,0,No,No,2,Yes,No,Fiber Optic,No,...,No,Month-To-Month,Yes,Electronic check,70.70,151.65,Yes,High,Low,New

In [1446]:
#save the cleaned data first
df.to_csv('cleaned_customer_churn_data.csv',index=False)

In [1495]:
df.shape

(7043, 24)

In [1447]:
#create an engine
engine=create_engine(
    "mysql+pymysql://root:Terere#123@localhost/Customer_Churn_Analysis"
)

In [1448]:
#transfer the data to mysql for analysis 
df.to_sql(
    name="Customer_Churn_Analysis_Table",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!

C:\Users\hp\AppData\Local\Temp\ipykernel_18216\3540293896.py:2: UserWarning: The provided table name 'Customer_Churn_Analysis_Table' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(